%YAML 1.2
---

imports:
    - { resource: 'parameters.yml' }

parameters:
  LOG_PATH: /var/log

app:
  name: conditor-api

nodejs:
  stackTracelimit: 10

log:
  path: %env(HOME)%%env(LOG_PATH)%

express:
  api:
    host: %env(CONDITOR_API_HOST)%
    port: %env(CONDITOR_API_PORT)%

elastic:
  clients:
    main:
      hosts: %env(CONDITOR_ES_HOSTS)% # String, String[], Object[]
      apiVersion: %env(CONDITOR_ES_VERSION)%
      requestTimeout: 30000
      log: # Possible values: error, info, trace, warning, debug
        - error
