%YAML 1.2
---

imports:
  - resource: config.yml

security:
  reverseProxy: %env(REVERSE_PROXY)%, ::ffff:127.0.0.1 # we add supertest request ip so we can x-forward spoofed ip
  ip:
    inMemory:
      - 111.11.11.1
  jwt:
    forbidenIds:
      - forbidThisId
